# Generated by Django 5.0.6 on 2024-05-11 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomClient', models.CharField(max_length=120, verbose_name='Nom')),
                ('PrenomClient', models.CharField(max_length=120, verbose_name='Prénom')),
                ('Entreprise', models.CharField(max_length=120, verbose_name='Entreprise')),
                ('AdresseMail', models.EmailField(max_length=120, verbose_name='Adresse mail')),
                ('NumeroTelephone', models.CharField(max_length=120, verbose_name='Numéro de téléphone')),
            ],
        ),
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomFormateur', models.CharField(max_length=120, verbose_name='Nom du formateur')),
                ('PrenomFormateur', models.CharField(max_length=120, verbose_name='Prénom du formateur')),
                ('AdresseMail', models.EmailField(max_length=120, verbose_name='Adresse mail')),
                ('NumeroTelephone', models.CharField(max_length=120, verbose_name='Numéro de téléphone')),
            ],
        ),
        migrations.CreateModel(
            name='Superviseur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomSuperviseur', models.CharField(max_length=120, verbose_name='Nom du superviseur')),
                ('PrenomSuperviseur', models.CharField(max_length=120, verbose_name='Prénom du superviseur')),
                ('AdresseMail', models.EmailField(max_length=120, verbose_name='Adresse mail')),
                ('NumeroTelephone', models.CharField(max_length=120, verbose_name='Numéro de téléphone')),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomFormation', models.CharField(max_length=120, verbose_name='Nom de la formation')),
                ('DescriptionFormation', models.CharField(max_length=120, verbose_name='Description')),
                ('DateFormation', models.DateTimeField(max_length=120, verbose_name='Date de la formation')),
                ('NomClient', models.CharField(max_length=120, verbose_name='Nom du client')),
                ('LieuFormation', models.CharField(max_length=120, verbose_name='Lieu de la formation')),
                ('ResponsableFormation', models.CharField(max_length=120, verbose_name='Responsable de la formation')),
                ('Formateurs', models.ManyToManyField(blank=True, to='Events.formateur')),
                ('Participants', models.ManyToManyField(blank=True, to='Events.client')),
            ],
        ),
    ]
