# Generated by Django 5.0.6 on 2024-05-12 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='EtatValidation',
            field=models.BooleanField(blank=True, default=False, verbose_name='Etat de validation'),
        ),
    ]
